Repository GoogleCloudPlatform/community, pull requests merged in 2018-10, with the labels that each got.

#549 add tutorial demonstrating integration of Mender OTA software with Cloud IoT Core
  tutorials/cloud-iot-mender-ota/LICENSE
  tutorials/cloud-iot-mender-ota/auth-function/firebase.json
  tutorials/cloud-iot-mender-ota/auth-function/functions/package-lock.json
  tutorials/cloud-iot-mender-ota/auth-function/functions/package.json
  tutorials/cloud-iot-mender-ota/auth-function/functions/src/devices.ts
  tutorials/cloud-iot-mender-ota/auth-function/functions/src/index.ts
  tutorials/cloud-iot-mender-ota/auth-function/functions/src/mender-axios.ts
  tutorials/cloud-iot-mender-ota/auth-function/functions/src/useTest.ts
  tutorials/cloud-iot-mender-ota/auth-function/functions/tsconfig.json
  tutorials/cloud-iot-mender-ota/auth-function/functions/tslint.json
  tutorials/cloud-iot-mender-ota/image/mender-gcp-build.sh
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/COPYING.MIT
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/LICENSE
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/README
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/conf/layer.conf
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/recipes-gcp/gcp-config/files/LICENSE
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/recipes-gcp/gcp-config/files/gcp-config.sh
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/recipes-gcp/gcp-config/gcp-config_1.0.bb
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/recipes-gcp/gcp-root-certs/gcp-root-certs_git.bb
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/recipes-gcp/images/gcp-mender-demo-image.bb
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/recipes-gcp/mender-google-activation-agent/files/LICENSE
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/recipes-gcp/mender-google-activation-agent/files/activate_agent.py
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/recipes-gcp/mender-google-activation-agent/files/mender-google-activation-agent.service
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/recipes-gcp/mender-google-activation-agent/files/wait-for-timesync
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/recipes-gcp/mender-google-activation-agent/mender-google-activation-agent.bb
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/recipes-gcp/python-docs-samples/files/mqtt-example.service
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/recipes-gcp/python-docs-samples/files/start-mqtt-example.sh
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/recipes-gcp/python-docs-samples/python-docs-samples_git.bb
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/recipes-mender/mender-gcp-delay-server-connection/files/LICENSE
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/recipes-mender/mender-gcp-delay-server-connection/files/server-connection-check
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/recipes-mender/mender-gcp-delay-server-connection/mender-gcp-delay-server-connection_1.0.bb
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/recipes-mender/mender/files/gcp-iot-mender-device-identity
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/recipes-mender/mender/files/mender-generate-certificate
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/recipes-mender/mender/files/mender.conf
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/recipes-mender/mender/mender-gcp-iot.inc
  tutorials/cloud-iot-mender-ota/image/meta-gcp-iot/recipes-mender/mender/mender_%.bbappend
  tutorials/cloud-iot-mender-ota/image/readme.md
  tutorials/cloud-iot-mender-ota/image/update-image.sh
  tutorials/cloud-iot-mender-ota/images/Mender-on0.png
  tutorials/cloud-iot-mender-ota/images/Mender-on1.png
  tutorials/cloud-iot-mender-ota/images/Mender-on10.png
  tutorials/cloud-iot-mender-ota/images/Mender-on11.png
  tutorials/cloud-iot-mender-ota/images/Mender-on12.png
  tutorials/cloud-iot-mender-ota/images/Mender-on2.png
  tutorials/cloud-iot-mender-ota/images/Mender-on3.png
  tutorials/cloud-iot-mender-ota/images/Mender-on4.png
  tutorials/cloud-iot-mender-ota/images/Mender-on5.png
  tutorials/cloud-iot-mender-ota/images/Mender-on6.png
  tutorials/cloud-iot-mender-ota/images/Mender-on7.png
  tutorials/cloud-iot-mender-ota/images/Mender-on8.png
  tutorials/cloud-iot-mender-ota/images/Mender-on9.png
  tutorials/cloud-iot-mender-ota/index.md
  tutorials/cloud-iot-mender-ota/server/mender_server_install.sh
  tutorials/cloud-iot-mender-ota/server/prod.yml
Labels: cla, new tutorial

#558 Update index.md
  tutorials/kotlin-ktor-app-engine-java8/index.md
Labels: cla: yes

#567 Upgrade to CircleCI 2.0
  .circleci/config.yml
  .circleci/npm-install-retry.js
  .gitignore
  circle.yml
  package.json
  tutorials/cloud-functions-avro-import-bq/index.js
  tutorials/cloud-iot-rtdp/function/index.js
  tutorials/understanding-oauth2-and-deploy-a-basic-auth-srv-to-cloud-functions/code/function.js
  yarn.lock
Labels: cla: yes

#555 Replace 'Apache Dropwizard' with just 'Dropwizard'
  tutorials/appengine-dropwizard/index.md
Labels: cla: yes

#553 Secure Jupyter Notebook Server with Julia 1.0 Kernel Installed
  tutorials/julia-jupyter-notebook-server/acme-cert.sh
  tutorials/julia-jupyter-notebook-server/index.md
  tutorials/julia-jupyter-notebook-server/install-julia.sh
  tutorials/julia-jupyter-notebook-server/jupyter-config.sh
  tutorials/julia-jupyter-notebook-server/main.tf
  tutorials/julia-jupyter-notebook-server/secure-jupyter-interface.png
  tutorials/julia-jupyter-notebook-server/secure-jupyter-login.png
  tutorials/julia-jupyter-notebook-server/self-signed-cert.sh
  tutorials/julia-jupyter-notebook-server/setup.sh
  tutorials/julia-jupyter-notebook-server/start-jupyter.sh
  tutorials/julia-jupyter-notebook-server/variables.tf
Labels: cla: no, new tutorial

#575 Fixes #574 - Update automated publishing doc to give correct menu name
  tutorials/automated-publishing-cloud-build/add-trigger-button.png
  tutorials/automated-publishing-cloud-build/index.md
Labels: cla: yes

#579 fixing author name to be GitHub user name
  tutorials/gke-filestore-dynamic-provisioning/index.md
Labels: cla: yes
