Repository GoogleCloudPlatform/community, pull requests merged in 2019-03, with the labels that each got.

#765 Update index.md
  tutorials/https-load-balancing-nginx/index.md
Labels: cla: yes

#767 replacing ampersand with HTML character reference
  tutorials/run-spring-petclinic-on-app-engine-cloudsql/index.md
Labels: cla: yes

#740 Asynchronous patterns for Cloud Functions
  tutorials/cloud-functions-async/create-test/main.go
  tutorials/cloud-functions-async/functions.go
  tutorials/cloud-functions-async/go.mod
  tutorials/cloud-functions-async/go.sum
  tutorials/cloud-functions-async/image/arch.png
  tutorials/cloud-functions-async/image/stateful-job.png
  tutorials/cloud-functions-async/image/sync-request.png
  tutorials/cloud-functions-async/image/work-queue.png
  tutorials/cloud-functions-async/index.md
  tutorials/cloud-functions-async/worker/main.go
Labels: cla: yes, new tutorial

#772 iot: removed unused arguments from gateway client, update md links
  tutorials/cloud-iot-gateways-rpi/cloudiot_mqtt_gateway.py
  tutorials/cloud-iot-gateways-rpi/index.md
  tutorials/cloud-iot-gateways-rpi/run-gateway
Labels: cla: yes

#771 IoT Monitoring tutorial with Prometheus
  tutorials/cloud-iot-prometheus-monitoring/alert-function/main.py
  tutorials/cloud-iot-prometheus-monitoring/dashboards/Device Detail View-1545166082880.json
  tutorials/cloud-iot-prometheus-monitoring/dashboards/Region Dashboard-1545166109026.json
  tutorials/cloud-iot-prometheus-monitoring/dashboards/stackdriver-example-1545324674962.json
  tutorials/cloud-iot-prometheus-monitoring/helm-rbac.yaml
  tutorials/cloud-iot-prometheus-monitoring/images/architecture.png
  tutorials/cloud-iot-prometheus-monitoring/images/extractor.png
  tutorials/cloud-iot-prometheus-monitoring/images/iot-monitoring-tutorial0.png
  tutorials/cloud-iot-prometheus-monitoring/images/iot-monitoring-tutorial1.png
  tutorials/cloud-iot-prometheus-monitoring/images/promiot.png
  tutorials/cloud-iot-prometheus-monitoring/index.md
  tutorials/cloud-iot-prometheus-monitoring/iotmonitor-chart/.helmignore
  tutorials/cloud-iot-prometheus-monitoring/iotmonitor-chart/Chart.yaml
  tutorials/cloud-iot-prometheus-monitoring/iotmonitor-chart/readme.md
  tutorials/cloud-iot-prometheus-monitoring/iotmonitor-chart/requirements.yaml
  tutorials/cloud-iot-prometheus-monitoring/iotmonitor-chart/templates/NOTES.txt
  tutorials/cloud-iot-prometheus-monitoring/iotmonitor-chart/templates/_helpers.tpl
  tutorials/cloud-iot-prometheus-monitoring/iotmonitor-chart/templates/alert-viewer.yaml
  tutorials/cloud-iot-prometheus-monitoring/iotmonitor-chart/templates/simulator.yaml
  tutorials/cloud-iot-prometheus-monitoring/iotmonitor-chart/values.yaml
  tutorials/cloud-iot-prometheus-monitoring/simulator/Dockerfile
  tutorials/cloud-iot-prometheus-monitoring/simulator/US-cities.csv
  tutorials/cloud-iot-prometheus-monitoring/simulator/build-container
  tutorials/cloud-iot-prometheus-monitoring/simulator/main.go
  tutorials/cloud-iot-prometheus-monitoring/simulator/simdevice.go
  tutorials/cloud-iot-prometheus-monitoring/web-proxy/app.yaml
  tutorials/cloud-iot-prometheus-monitoring/web-proxy/proxy.go
Labels: cla: yes, new tutorial

#776 fixing issue 773
  tutorials/managing-gcp-projects-with-terraform/index.md
Labels: cla: yes

#768 Pubsub automated archiver
  tutorials/cloud-pubsub-drainer/channel.json
  tutorials/cloud-pubsub-drainer/drainer-func/cmd/main.go
  tutorials/cloud-pubsub-drainer/drainer-func/function.go
  tutorials/cloud-pubsub-drainer/drainer-func/go.mod
  tutorials/cloud-pubsub-drainer/drainer-func/go.sum
  tutorials/cloud-pubsub-drainer/image/architecture.png
  tutorials/cloud-pubsub-drainer/image/cloud_storage_export.png
  tutorials/cloud-pubsub-drainer/image/stackdriver_alerting_policy.png
  tutorials/cloud-pubsub-drainer/image/stackdriver_archiver_function_logs.png
  tutorials/cloud-pubsub-drainer/image/stackdriver_relay_function_logs.png
  tutorials/cloud-pubsub-drainer/index.md
  tutorials/cloud-pubsub-drainer/loader/cities.csv
  tutorials/cloud-pubsub-drainer/loader/main.go
  tutorials/cloud-pubsub-drainer/policy.json
Labels: cla: yes, new tutorial

#646 Adding PCI DSS Tokenization tutorial
  tutorials/pci-tokenizer/.gcloudignore
  tutorials/pci-tokenizer/.gitignore
  tutorials/pci-tokenizer/Dockerfile
  tutorials/pci-tokenizer/config/default.json
  tutorials/pci-tokenizer/index.js
  tutorials/pci-tokenizer/index.md
  tutorials/pci-tokenizer/package.json
  tutorials/pci-tokenizer/src/deploy-detokenize.sh
  tutorials/pci-tokenizer/src/deploy-tokenize.sh
  tutorials/pci-tokenizer/src/docker_entrypoint.sh
  tutorials/pci-tokenizer/src/docker_run.sh
  tutorials/pci-tokenizer/src/getToken.js
  tutorials/pci-tokenizer/src/server.js
Labels: cla: yes

#779 escaping angle brackets for DevSite publishing
  tutorials/appengine-pusher/index.md
Labels: cla: yes

#780 fixing date
  tutorials/cloud-pubsub-drainer/index.md
Labels: cla: yes

#781 fixing the publication date
  tutorials/pci-tokenizer/index.md
Labels: cla: yes

#782 converting from angle brackets
  tutorials/cdn-fastly.md
Labels: cla: yes

#786 Troubleshooting a potential security/perms issue
  tutorials/cbt-import-csv.md
Labels: cla: yes

#784 using square brackets instead of angle brackets
  tutorials/cloud-iot-hybrid/index.md
Labels: cla: yes

#788 escaping angle brackets
  tutorials/cloudbuild-angular-universal/index.md
Labels: cla: yes

#787 repalcing angle brackets with square brackets
  tutorials/cloud-iot-logging/index.md
Labels: cla: yes

#789 escaping angle brackets
  tutorials/developing-services-with-k8s.md
Labels: cla: yes

#783 escaping angle brackets
  tutorials/cloud-iot-firestore-config/index.md
Labels: cla: yes

#790 escaping angle brackets
  tutorials/envoy-flask-google-container-engine.md
Labels: cla: yes

#791 another batch of angle bracket fixes
  tutorials/get-started-bitnami-django.md
  tutorials/install-bower-dependencies-on-google-app-engine.md
  tutorials/ios-chatbot-part-2/index.md
  tutorials/ios-chatbot-part-3/index.md
  tutorials/iot-device-to-device/index.md
  tutorials/kubernetes-auth-openid-rbac.md
Labels: cla: yes

#792 escaping angle brackets
  tutorials/ssh-port-forwarding-set-up-load-testing-on-compute-engine/index.md
Labels: cla: yes

#793 dealing with angle brackets
  archived/setting-up-lemp.md
  tutorials/on-beyond-magpie2.md
  tutorials/puppet-in-google-cloud-platform.md
  tutorials/run-botkit-on-google-container-engine/index.md
  tutorials/setting-up-postgres-hot-standby.md
  tutorials/setting-up-postgres.md
  tutorials/setting-up-ruby-discourse.md
  tutorials/ssh-tunnel-on-gce.md
  tutorials/using-cloud-vpn-with-cisco-asr/index.md
  tutorials/wix-media-python.md
Labels: cla: yes

#794 Update index.md
  tutorials/managing-gcp-projects-with-terraform/index.md
Labels: cla: yes

#797 fixing branding issue
  tutorials/cdn-fastly.md
Labels: cla: yes

#798 Updating published solution URL
  tutorials/pci-tokenizer/index.md
Labels: cla: yes

#778 initial release
  tutorials/ardu-pi-serial-part-2/architecture.png
  tutorials/ardu-pi-serial-part-2/beam-requirements.txt
  tutorials/ardu-pi-serial-part-2/beam-solarwind.py
  tutorials/ardu-pi-serial-part-2/bq-data.jpg
  tutorials/ardu-pi-serial-part-2/bq-query-res.png
  tutorials/ardu-pi-serial-part-2/bq-schema.jpg
  tutorials/ardu-pi-serial-part-2/df-job.png
  tutorials/ardu-pi-serial-part-2/ds-report.jpg
  tutorials/ardu-pi-serial-part-2/gcreate.png
  tutorials/ardu-pi-serial-part-2/index.md
  tutorials/ardu-pi-serial-part-2/select_fields.png
  tutorials/ardu-pi-serial-part-2/setup.py
  tutorials/ardu-pi-serial-part-2/solarwindreport.ipynb
Labels: cla: yes

#801 Enable all APIs, minor formatting changes
  tutorials/cloud-functions-async/index.md
Labels: cla: yes

#802 Ardu pi serial part 1 update
  tutorials/ardu-pi-serial-part-1/index.md
Labels: cla: yes

#804 Update index.md
  tutorials/singularity-containers-with-cloud-build/index.md
Labels: cla: yes

#648 Adding Container Optimized OS file integrity monitoring tutorial
  tutorials/gcp-cos-basic-fim/Dockerfile
  tutorials/gcp-cos-basic-fim/LICENSE
  tutorials/gcp-cos-basic-fim/basic-fis-daemonset.yaml
  tutorials/gcp-cos-basic-fim/build
  tutorials/gcp-cos-basic-fim/index.md
  tutorials/gcp-cos-basic-fim/scan.sh
  tutorials/gcp-cos-basic-fim/start.py
Labels: cla: yes

#647 Adding Container Optimized OS antivirus scan tutorial
  tutorials/gcp-cos-clamav/Dockerfile
  tutorials/gcp-cos-clamav/LICENSE
  tutorials/gcp-cos-clamav/build
  tutorials/gcp-cos-clamav/clamav-daemonset.yaml
  tutorials/gcp-cos-clamav/conf/clamd.conf
  tutorials/gcp-cos-clamav/conf/freshclam.conf
  tutorials/gcp-cos-clamav/health.sh
  tutorials/gcp-cos-clamav/index.md
  tutorials/gcp-cos-clamav/scan.sh
  tutorials/gcp-cos-clamav/start.py
Labels: cla: yes

#480 Exporting Stackdriver events to Elastic Cloud
  tutorials/exporting-stackdriver-elasticcloud/cloud_shell_icon.png
  tutorials/exporting-stackdriver-elasticcloud/copy_es_uri.png
  tutorials/exporting-stackdriver-elasticcloud/create_es_deployment.png
  tutorials/exporting-stackdriver-elasticcloud/define_index_pattern.png
  tutorials/exporting-stackdriver-elasticcloud/enable_apis.png
  tutorials/exporting-stackdriver-elasticcloud/es_deployment_launch.png
  tutorials/exporting-stackdriver-elasticcloud/es_trial.png
  tutorials/exporting-stackdriver-elasticcloud/index.md
  tutorials/exporting-stackdriver-elasticcloud/index_pattern_timestamp.png
  tutorials/exporting-stackdriver-elasticcloud/kibana_index_patterns.png
  tutorials/exporting-stackdriver-elasticcloud/kibana_log_flow.png
  tutorials/exporting-stackdriver-elasticcloud/kibana_login.png
  tutorials/exporting-stackdriver-elasticcloud/kibana_url.png
  tutorials/exporting-stackdriver-elasticcloud/stackdriver_es_architecture.png
Labels: cla: yes, new tutorial

#805 copy-edit and branding details
  tutorials/go-gae-quickstart.md
Labels: cla: yes

#754 updated moniker instructions + generalized Verisign DNSSEC Analyzer tool
  tutorials/dnssec-cloud-dns-domains/index.md
Labels: cla: yes

#807 fixing production issues found on staging
  tutorials/dotnet-mvms-quickstart.md
  tutorials/exporting-stackdriver-elasticcloud/index.md
  tutorials/gcp-cos-basic-fim/index.md
  tutorials/gcp-cos-clamav/index.md
  tutorials/java-gae-quickstart.md
  tutorials/nodejs-gae-quickstart.md
  tutorials/php-gae-quickstart.md
  tutorials/php-mvms-quickstart.md
  tutorials/python-gae-quickstart.md
  tutorials/python-mvms-quickstart.md
  tutorials/ruby-mvms-quickstart.md
Labels: cla: yes

#808 fixing heading level
  tutorials/gcp-cos-clamav/index.md
Labels: cla: yes

#810 minor tweak as part of troubleshooting investigation
  tutorials/exporting-stackdriver-elasticcloud/index.md
Labels: cla: yes

#811 Updated sigfox-api.py command line tool
  tutorials/sigfox-gw/sigfox-api.py
Labels: cla: yes, update needed

#812 correcting reference to App Engine flexible environment
  tutorials/php-mvms-quickstart.md
Labels: cla: yes
